### PR TITLE
Tag read write additions

### PR DESCRIPTION
**Pull request by jhenson29**
Added support for additional tag references
  -Array Elements
  -Integer Bits (Bit Index) (writing a bit index required addition of READ_MODIFY_WRITE_TAG service)
Added support for program name prefix for tags (in additional to current method of passing program name separately)
Updated tagname validation
Fixed bug for reading BOOL

### Description, Motivation, and Context

Some atomic tag names were not able used
  -Array Elements
  -Integer Bits (Bit Index) 
Program name tag prefixes allows the creation of program scope tags with a single string
Prevous tag name validation wouldn't pass new tag names and would pass other invalid tag names
BOOL tags always returned false the value was checked against 0x01 instead of 0xff

## How Has This Been Tested?

Tested reading/writing
  -tested different read/write methods
    -individual
    -group
    -scan
  -tested tags:
    -BOOL, SINT, INT, DINT, REAL
    -INT[x], SINT[x], DINT[x], DINT[x,x], DINT[x,x,x]
    -SINT.0-7, INT.0-15, DINT.0-31
    -DINT[x].x
    -Tag.DINTmember[x]
    -Tag.DINTmember.x
    -Tag.DINTmember[x].x
  -visually inspected IOI paths for various tags and checked them against the manuals

Tested reading/writing tags with both methods of creating program tags
  -pass program as value
  -prefix program to tag name

Tested new tag name validation
  -tested new regex extensively regex101.com as well as adding new tagname tests to tag.spec.js
  -tested new tag/member length validation and added tests to tagspec.js

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] This is a work in progress, and I want some feedback (If yes, please mark it in the title -> e.g. `[WIP] Some awesome PR title`)

### CODE REVIEW

**Comment by patrickjmcd** [comment]
A couple of notes:

- reading the base tag of an array returns the value of the 0'th position
- reading a BOOL[x] tag results in `Unrecognized Type Passed Read from Controller`
- I'm not sure if it was failing before, but tagname validation fails for Local tags like `Local:1:I.Data.3`

Reading array elements of REAL, DINT, and INT are all working for me. Reading bit elements of DINT and INT are working as well

**Comment by cmseaton42** [comment]
@patrickjmcd These are the notes you made from testing of the PR, correct? If so, lets get those things resolved and I will pull this.  Thanks again for the contributions @jhenson29!

**Comment by patrickjmcd** [comment]
yes, testing the PR

**Comment by jhenson29** [comment]
I fixed bool arrays and module defined tags.

The only issue with bool arrays is that you HAVE to pass in `BIT_STRING` for the data type. The actual read returns `0xd3` (`BIT_STRING`) and 4 bytes of data. The array index you request is in 4 byte increments, then you have to treat the offset as a bit index. e.g. If you have a data type `BOOL[64]` and you want to read `tag[44]`, it has to be done as `tag[1].12`. The module does this internally, (e.g the user still just sets it as `tag[44]`) but the module has to know to do it by passing in `BIT_STRING`. If you try to read `tag[44]`, it will error because it's trying to access an index (`tag[44*32]`) that doesn't exist.

**Comment by cmseaton42** [comment]
I finally have some down time! I am checking this out now locally.  Will provide feedback by end of day! Sorry about the delay.

**Comment by cmseaton42** [comment]
Thanks again for the help. Everything looks good. I updated the semver version to denote a feature addition. I am going to release these changes to `v1.2.0`

**Pull request merged**
